config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'tasks', to: 'tasks#tasks'
  resources :users
  resources :tasks, only: [:create, :destroy, :edit, :show, :update]
  resources :groups
  resources :groups do
    member do
      get :join
      get :defection
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy
  accepts_nested_attributes_for :group_users, allow_destroy: true
  validates :name, presence: true, length: { maximum: 30 }

  # グループの作成者を返す
  def owner
    User.find_by(id: self.owner_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :owner, only: [:edit, :update, :destroy]

  def index
    @groups = Group.paginate(page: params[:page])
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    # グループ作成者は自動的に当該グループに所属する
    @group.users << current_user
    # 作成者はownerとして登録される
    @group.owner_id = current_user.id
    if @group.save
      flash[:success] = "新規グループを作成しました"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      flash[:success] = "グループ情報を更新しました"
      redirect_to @group
    else
      render 'edit'
    end
  end

  def join
    @group = Group.find(params[:id])
    # グループに所属していなければ追加
    unless @group.users.include?(current_user)
      flash[:success] = "「#{@group.name}」に参加しました"
      @group.users << current_user
    else
      flash[:danger] = "あなたはすでに「#{@group.name}」のメンバーです"
    end
    redirect_to group_url
  end

  def defection
    @group = Group.find(params[:id])
    # 作成者じゃなく、かつグループに参加していれば退会
    if @group.owner_id == current_user.id
      flash[:danger] = "あなたはこのグループの作成者のため、退会する場合はグループ自体を削除して下さい"
      render 'show'
    elsif @group.users.include?(current_user)
      flash[:success] = "#{@group.name}グループから退会しました"
      @group.group_users.find_by(user_id: current_user).destroy
      redirect_to groups_url
    end
  end

  def destroy
    @group = Group.find(params[:id])
    group_name = @group.name
    @group.destroy
    flash[:success] = "「#{group_name}」グループを削除しました"
    redirect_to groups_url
  end

  private

    def group_params
      params.require(:group).permit(:name)
    end

    def owner
      @group = Group.find(params[:id])
      unless @group.owner_id == current_user.id
        flash[:danger] = "グループの編集／削除は作成者のみが行えます"
        redirect_to @group
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
  # ログインユーザーがそのグループの作成者か？
  def is_owner?(group)
    if group.owner == current_user
      return true
    else
      return false
    end
  end

  # 既に参加済みのユーザーか？
  def is_member?(group)
    group.users.include?(current_user)
  end
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label "グループ名" %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/groups/_group.html.erb
<li>
  <%= link_to group.name, group %>
</li>

app/views/groups/edit.html.erb
<% provide(:title, "グループ編集") %>
<% provide(:button_text, "更新") %>
<h1><%= @group.name %></h1>

<%= render 'form' %>

app/views/groups/index.html.erb
<% provide(:title, "グループ一覧") %>
<div class="group-list">
  <h1>グループ一覧</h1>

  <%= will_paginate %>

  <table class="table">
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td><%= link_to group.name, group %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<% provide(:title, "グループ一覧") %>
<% provide(:button_text, "作成") %>
<h1>グループ作成</h1>

<%= render 'form' %>

app/views/groups/show.html.erb
<% provide(:title, "グループ詳細") %>
<div class="group-show">
  <h1><%= @group.name %></h1>

  <table class="table">
    <tbody>
      <% @group.users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% unless is_member?(@group) %>
    <%= link_to '参加', join_group_path, class: "btn btn-success" %>
  <% end %>
  <% if is_member?(@group) and @group.owner_id != current_user.id %>
    <%= link_to '退会', defection_group_path, class: "btn btn-warning" %>
  <% end %>
  <% if is_owner?(@group) %>
    <%= link_to "編集", edit_group_path, class: "btn btn-primary" %>
    <%= link_to "削除", group_path, method: :delete, 
                class: 'btn btn-danger',
                data: { confirm: "本当に削除しますか？" } %>
  <% end %>
</div>